/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import proyecto_jh.Function;
import static Windows.wMain.tabla;
import javax.swing.JOptionPane;
import proyecto_jh.Document;
import proyecto_jh.Order;
import proyecto_jh.Searches;

/**
 *
 * @author Usuario
 */
public class wAnalyze extends javax.swing.JFrame {

    public static wMenu v1;
    
    public wAnalyze(wMenu v1) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();
        showDocuments = new javax.swing.JButton();
        selectDoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        screen.setColumns(20);
        screen.setRows(5);
        jScrollPane1.setViewportView(screen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 540, 200));

        showDocuments.setText("VER DOCUMENTOS DISPONIBLES");
        showDocuments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDocumentsActionPerformed(evt);
            }
        });
        jPanel1.add(showDocuments, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        selectDoc.setText("SELECCIONAR");
        selectDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDocActionPerformed(evt);
            }
        });
        jPanel1.add(selectDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Analizar Resumen ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        back.setText("⬅️");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        wMenu menu = new wMenu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void showDocumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDocumentsActionPerformed
        Function func = new Function();
        Order orden = new Order();
        String info = func.showAllDocuments(tabla);
        String[] docs = orden.createArrayOfDocs(info);
        String[] newArray = orden.orderAlphabetic(docs);
        String information = orden.printNewArray(newArray);
        screen.setText(information);
    }//GEN-LAST:event_showDocumentsActionPerformed

    private void selectDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDocActionPerformed
        try {
            Function func = new Function();
            Searches searches = new Searches(tabla);
            String index_s = JOptionPane.showInputDialog(null, "Ingrese la clave del documento que desea analizar");
            int index = Integer.parseInt(index_s);
            Document doc = searches.searchDoc(index);
            String info = func.getInformationToAnalyze(doc);
            screen.setText(info);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar el documento\n Asegúrese de ingresar correctamente la clave única del documento");
        }
    }//GEN-LAST:event_selectDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wAnalyze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wAnalyze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wAnalyze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wAnalyze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wAnalyze(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea screen;
    private javax.swing.JButton selectDoc;
    private javax.swing.JButton showDocuments;
    // End of variables declaration//GEN-END:variables
}
